name: change_user
description: "Change Networks Gallery (Desktop + Mobile)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.5

  # Animations & UI effects
  lottie: ^3.3.1
  glassmorphism: ^3.0.0
  flutter_animate: ^4.5.0

  # HTTP & Networking
  http: ^1.4.0
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8


  # Routing
  go_router: ^14.2.0

  # Fonts & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Storage & File handling
  shared_preferences: ^2.3.2
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/
